npmPublishRegistry: "https://nmtsoft-npm.pkg.coding.net/firefly/main/"
npmRegistries:
  //nmtsoft-npm.pkg.coding.net/firefly/main/:
    _password: ${PKG_PASSWORD}
    username: firefly-blog-deploy
    email: haozhennan@outlook.com
