menu:
  存档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  版本: /publish/ || fas fa-timeline
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

theme_color:
  enable: true
  # main: "#49B1F5"
  paginator: "#49B1F5"
  # button_hover: "#FF7242"
  text_selection: "#49B1F5"
  # link_color: "#99a9bf"
  # meta_color: "#858585"
  # hr_color: "#A4D8FA"
  # code_foreground: "#F47466"
  # code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#49B1F5"
  # blockquote_padding_color: "#49b1f5"
  # blockquote_background_color: "#49b1f5"
  # scrollbar_color: "#49b1f5"

aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: View on github
      link: https://github.com/nmtsoft/hexo-theme-firefly

footer:
  owner:
    enable: true
    since: 2022
  custom_text:
  upyun: true
  icp:
    enable: true
    text: 冀ICP备18006888号-2
    url: https://beian.miit.gov.cn/
    icon: /img/icp.png
  copyright: true

search:
  use: local
  algolia:
    hits:
      per_page: 6
  local:
